In [24]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np

In [2]:
dataset = pd.read_csv('50_Startups.csv')

In [3]:
dataset = pd.get_dummies(dataset, drop_first = True)

In [4]:
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='object')

In [5]:
independent = dataset.drop(['Profit'], axis =1)

In [6]:
dependent = dataset['Profit']

In [7]:
xtrain, xtest,ytrain,ytest = train_test_split(independent, dependent, test_size = 0.25, random_state = 0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

xtrain = sc.fit_transform(xtrain)
xtest = sc.transform(xtest)

In [13]:
scy = StandardScaler()
rs_ytrain = ytrain.values.reshape(-1,1)
rs_ytest = ytest.values.reshape(-1,1)
ytrain = scy.fit_transform(rs_ytrain)
ytest = scy.transform(rs_ytest)

In [14]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf', C= 1000)
regressor.fit(xtrain,ytrain)

C:\Users\Ilango\AppData\Local\anaconda3\envs\aiml\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1000, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
    gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
    tol=0.001, verbose=False)

In [15]:
ypred = regressor.predict(xtest)
from sklearn.metrics import r2_score
rscore = r2_score(ytest,ypred)

rscore

0.5171304577504372

In [18]:
filename = "finalizedmodel.sav"
import pickle
pickle.dump(regressor,open(filename,'wb'))

scfilename = 'scalerX.sav'
pickle.dump(sc,open(scfilename,'wb'))

scyfilename = 'scalery.sav'
pickle.dump(scy,open(scyfilename,'wb'))

In [19]:
preinput = sc.transform([[1300,12000,4000,0,1]])
preinput

array([[-1.49512511, -4.37279969, -1.56079131, -0.52522573,  1.35873244]])

In [22]:
loadedmodel = pickle.load(open('finalizedmodel.sav','rb'))
result = loadedmodel.predict(preinput)
result

array([-1.06062696])

In [27]:
preoutput = scy.inverse_transform(result)
preoutput

array([65739.32412574])